name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Checkout code
      uses: actions/checkout@v4      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pyshark matplotlib pandas coverage
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: coverage run
      run: coverage run -m pytest test_unit_integration.py
    - name: coverage report
      run: coverage report
    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERUSER }}
        password: ${{ secrets.DOCKERPW }}
    - name: docker build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          efleming20/cs333_final_project:${{ secrets.GH_TOKEN }}
          efleming20/cs333_final_project:latest
